# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 06:32
from __future__ import unicode_literals

from django.db import migrations
import django_pgjsonb.fields
import ejson


class Migration(migrations.Migration):

    dependencies = [
        ('dddp', '0009_auto_20150812_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='params_ejson',
            field=django_pgjsonb.fields.JSONField(decode_kwargs={b'cls': ejson.EJSONDecoder}, default={}, encode_kwargs={b'cls': ejson.EJSONEncoder}),
        ),
    ]
