# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddp', '0010_auto_20160217_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
