# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddp', '0011_subscription_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='pid',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
