# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dddp', '0012_connection_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncollection',
            name='collection_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriptioncollection',
            name='model_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
